version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./dbdata:/var/lib/mysql
     restart: always
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: sentiment
       MYSQL_USER: dev
       MYSQL_PASSWORD: dev
     container_name: mysql_db
